### ISSUE TITLE
ImportError: No module named 'fcntl'

### ISSUE THREAD

**Issue by alexandrul** [jenmud/module-dependencies#1]
```
funnel-web robotframework
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\Scripts\funnel-web.exe\__main__.py", line 5, in <module>
  File "c:\python35\lib\site-packages\funnel_web\__main__.py", line 7, in <module>
    from funnel_web.scrape import scrape, run_server
  File "c:\python35\lib\site-packages\funnel_web\scrape.py", line 6, in <module>
    from ruruki.graphs import Graph
  File "c:\python35\lib\site-packages\ruruki\graphs.py", line 10, in <module>
    from ruruki.locks import DirectoryLock
  File "c:\python35\lib\site-packages\ruruki\locks.py", line 6, in <module>
    import fcntl
ImportError: No module named 'fcntl'
```

**Comment by alexandrul** [comment]
I was able to also install it on Python 3.5 under Windows, even if it's not Python 3.x compatible.

**Comment by alexandrul** [comment]
The good part is that I was able to use it thanks to the workaround from here: http://stackoverflow.com/a/25471508/19756

**Comment by jenmud** [comment]
Thanks @alexandrul for the workaround. There is a existing bug ticket open for ruruki with the exact issue (https://github.com/optiver/ruruki/issues/34) using it on windows. But this workaround is gold and I will be adding it into ruruki to get around the issue on windows. Thanks for your help and feedback.

It is only version and any other suggestions and comments are welcome.

Hope you are finding it useful.

**Comment by techtonik** [comment]
Going without locks seems dangerous, no?

**Comment by techtonik** [comment]
Maybe an explicit warning on Windows can be produced to explain consequences of that missing component?

**Comment by jenmud** [comment]
Nah not if you are using in-memory. Locks was only introduced to the persistent graph to avoid multiple graph databases from access'ing the same file descriptors and changing to state.

**Comment by jenmud** [comment]
That is a really good idea.

**Comment by jenmud** [comment]
I am closing the following issue, as it is logged under ruruki. See optiver/ruruki#34
